sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mbcatubig14/devops-tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true mbcatubig14/devops-tutorial npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'devops-tutorial'
  env: 'DevopsTutorial-env-1'
  bucket_name: 'elasticbeanstalk-eu-west-2-732232335702'
  bucket_path: 'devops-tutorial'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
